// Generated by CoffeeScript 1.8.0
$(function() {
  var l, m, n, p, v;
  l = 24;
  p = 5 * Math.pow(10, -5);
  m = 8;
  n = 30000;
  v = 20000;
  config.define({
    title: 'p<sub>ош</sub>',
    "default": p,
    valid: function(v) {
      return v > 0 && v < 1;
    },
    change: function(v) {
      return p = v;
    },
    $: {
      min: Math.pow(10, -8),
      max: 1 - Math.pow(10, -8),
      step: 10 * -5
    }
  });
  config.define({
    title: 'Число неинформационных элементов в блоке l',
    "default": l,
    valid: function(v) {
      return l > 1;
    },
    change: function(v) {
      return l = v;
    }
  });
  config.define({
    title: 'Число повторяемых при переспросе комбинаций M',
    "default": m,
    valid: function(v) {
      return v > 1;
    },
    change: function(v) {
      return m = v;
    }
  });
  config.define({
    title: 'Общее число переданных кадров N',
    "default": n,
    valid: function(v) {
      return n > 1;
    },
    change: function(v) {
      return n = v;
    }
  });
  config.define({
    title: 'Число переспросов V',
    "default": v,
    valid: function(v_) {
      return v_ > 1;
    },
    change: function(v_) {
      return v = v_;
    }
  });
  $('#apply-config').button().click(function() {
    var data, f;
    f = function(k) {
      return (k / (k + 1)) * ((n - v * (m - l)) / n);
    };
    data = map_(frange(0, n, function(x) {
      if (x < 100) {
        return 10;
      } else {
        return 100;
      }
    }), function(k) {
      return [k, f(k)];
    });
    return $.plot("#plot", [data]);
  });
  return $('#apply-config').click();
});

//# sourceMappingURL=main.js.map
